name: Running Build and test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install pybuilder
      run: |
        pip install pybuilder
    - name: pyb installing dependencies
      run: |
        pyb install_dependencies
    - name: To run python build with tests and coverage
      run: |
        pyb -v
    - name: To run Flake8 for lint checks
      run: |
        pyb analyze